x = input("enter your name: ")
print("welcome to eox "+x)


demo_tuple = (2,4,6,9,5,3,7,8)
# x = max(demo_tuple)
# # x = sum(demo_tuple,6)
# print(x)
# x = sorted(demo_tuple)
# print(demo_tuple)
# x = slice(2,7)
# print(demo_tuple[x])
# x = max(demo_tuple)
# x = min(demo_tuple)
# print(x)
k = iter(demo_tuple)
# print(i)
j = reversed(demo_tuple)
# print(j)
print(next(k))
print(next(j))
print(next(k))
print(next(j))
