cities = ["Mysore","Mysore","Bengaluru","Delhi","Texas"]
print(cities)
# cities.append("Dallas")
# cities.insert(2,"dallas")
# cities.remove("Delhi")
cities.pop(2)
# print(cities.index("Delhi"))
# print(cities.count("Mysore"))
# cities.sort()
# cities.reverse()
# new_cities = cities.copy()
# # print(cities)
# print(new_cities)
# print(new_cities.clear())
