demo_set1 = {"delhi","Mysore","Texas"}
demo_set2 = {"delhi","Mysore","Texas","China","Mysore","Turkey"}
# print(demo_set1)
# demo_set1.add("Dallas")
# demo_set1.remove("delhi")
# demo_set1.discard("delhi")
# demo_set1.pop()
# demo_set1.clear()
# demo_set3 = demo_set1.union(demo_set2)
# print(demo_set3)
# demo_set1.update(demo_set2)
# print(demo_set1)
# demo_set3 = demo_set1.intersection(demo_set2)
# print(demo_set3)
# demo_set1.intersection_update(demo_set2)
# print(demo_set1)
# demo_set3 = demo_set1.symmetric_difference(demo_set2)
# print(demo_set3)
# demo_set1.symmetric_difference_update(demo_set2)
# print(demo_set1)
# demo_set3 = demo_set2.difference(demo_set1)
# print(demo_set3)
# demo_set2.difference_update(demo_set1)
# print(demo_set2)
# z = demo_set1.issubset(demo_set2)
# # print(z)
# z= demo_set1.issuperset(demo_set2)
# print(z)